=== stienheremans/sen2like/sen2cor3/SEN2COR_3/cfg/L2A_QUALITY.xsd
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!-- edited with XMLSpy v2016 sp1 (x64) (http://www.altova.com) by Christian Schmidt (Telespazio VEGA Deutschland GmbH) -->
<xs:schema xmlns="http://gs2.esa.int/DATA_STRUCTURE/l2aqiReport" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://gs2.esa.int/DATA_STRUCTURE/l2aqiReport" elementFormDefault="qualified" attributeFormDefault="unqualified" version="14">
	<xs:element name="L2A_Quality_File">
		<xs:annotation>
			<xs:documentation>L2AQI entry point of this xml file</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="L2aQualityFileType">
					<xs:sequence>
						<xs:element name="L2A_Quality_Header" type="L2aQualityHeaderType"/>
						<xs:element name="Data_Block" type="L2aQualityDataBlockType"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="report" type="ReportType">
		<xs:annotation>
			<xs:documentation>L2AQI report</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:simpleType name="PassFailType">
		<xs:annotation>
			<xs:documentation>type defining Passed/Failed/Error status</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse"/>
			<xs:enumeration value="PASSED"/>
			<xs:enumeration value="FAILED"/>
			<xs:enumeration value="ERROR"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="CcsdsDateType">
		<xs:restriction base="xs:string">
			<xs:length value="23"/>
			<xs:pattern value="UTC=\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="L2aQualityFileType">
		<xs:annotation>
			<xs:documentation>L2AQI standard File type</xs:documentation>
		</xs:annotation>
	</xs:complexType>
	<xs:complexType name="L2aQualityHeaderType">
		<xs:annotation>
			<xs:documentation>L2AQI header type</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Fixed_Header">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="File_Name" type="xs:string">
							<xs:annotation>
								<xs:documentation>The name of the file (c.f. L2AQI std: MMM_CCCC_TTTTTTTTTT_*instance_id*)
</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="File_Description" type="xs:string">
							<xs:annotation>
								<xs:documentation>Fixed string "File to use to configure Amalfi"</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="Notes" type="xs:string"/>
						<xs:element name="Mission">
							<xs:annotation>
								<xs:documentation>Fixed string : Mission ID extracted from filename (MMM = "S2_"|"S2A"|"S2B"|"S2P")</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="S2_"/>
									<xs:enumeration value="S2A"/>
									<xs:enumeration value="S2B"/>
									<xs:enumeration value="S2C"/>
									<xs:enumeration value="S2D"/>
									<xs:enumeration value="S2P"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="File_Class" type="xs:string">
							<xs:annotation>
								<xs:documentation>File_Class extracted form filename (i.e. "OPER") - not fixed here. Please note that the File Class will be set
“OPER” for all products generated during
the operation phase. During validation or for
internal testing other values can be defined. </xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="File_Type">
							<xs:annotation>
								<xs:documentation>File type extracted from filename "TTTTTTTTTT" = FFFFDDDDDD
   whereFile Category       : "FFFF" = "L2A_"
Semantic Descriptor : "DDDDDD" = "QLINFO" (See PSD-V05)
</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:length value="10"/>
									<xs:pattern value="L2A_QLINFO"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="Validity_Period">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Validity_Start" type="CcsdsDateType">
										<xs:annotation>
											<xs:documentation>Date of report creation</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="Validity_Stop" type="CcsdsDateType">
										<xs:annotation>
											<xs:documentation>MPA fixed end validity date for this file</xs:documentation>
										</xs:annotation>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="File_Version">
							<xs:annotation>
								<xs:documentation>must be the same as ../../../Data_Block/report/@version </xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:positiveInteger">
									<xs:totalDigits value="4"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="Source">
							<xs:annotation>
								<xs:documentation>source generated by MPA</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:sequence>
									<xs:element name="System" type="xs:string"/>
									<xs:element name="Creator" type="xs:string"/>
									<xs:element name="Creator_Version" type="xs:string"/>
									<xs:element name="Creation_Date" type="CcsdsDateType"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Variable_Header" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="L2aQualityDataBlockType">
		<xs:annotation>
			<xs:documentation>L2AQI datablock type</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element ref="report"/>
		</xs:sequence>
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="xml"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="InspectionType">
		<xs:attribute name="creation" type="xs:dateTime" use="required">
			<xs:annotation>
				<xs:documentation>When the inspection has been created.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="duration" type="xs:decimal" use="required">
			<xs:annotation>
				<xs:documentation>Elapsed time for this inspection.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="execution" type="xs:dateTime" use="required">
			<xs:annotation>
				<xs:documentation>When this inspection processing started.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The uniq identifier for this inspection. For sentinel-2 product. This identifier is prefixed with the S2 namespace. (i.e. "http://www.esa.int/s2#ispCategory")</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="item" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The item on which this inspection is attached. This item is not necessary the same as the one specified on the top level checklist definition. It can be a sub  item of the product.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="itemURL" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The URL pointing to the inspected item</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Human readable name of this inspection.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="priority" type="xs:byte" use="required">
			<xs:annotation>
				<xs:documentation>Priority level of this inspection</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="processingStatus" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The status of the inspection processing. Possible status in this report are "Done" when inspection performed, or "Canceled" if inspection process was cancelled.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="status" type="PassFailType" use="required">
			<xs:annotation>
				<xs:documentation>Inspection result status : "PASSED" if the inspection successully processed, "FAILED" if the inspection does not reach expected values or "ERROR" if the inspector raise an error.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ItemType">
		<xs:attribute name="url" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>the url to the item</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="className" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The human readable class name of this item.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>the human readable name of this item.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="class" type="xs:anyURI" use="required">
			<xs:annotation>
				<xs:documentation>Drb class</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="CheckListType">
		<xs:sequence>
			<xs:element name="parentID" type="xs:string">
				<xs:annotation>
					<xs:documentation>This field contains the name of L2AQI GIPP</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="name" type="xs:string">
				<xs:annotation>
					<xs:documentation> This field contains the  name of the checklist</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="version" type="xs:string">
				<xs:annotation>
					<xs:documentation> This field contains the  version of the checklist</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="item" type="ItemType">
				<xs:annotation>
					<xs:documentation>the root item on which this checklist is applied.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:sequence maxOccurs="unbounded">
				<xs:element name="check">
					<xs:annotation>
						<xs:documentation>results of processed check.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="inspection" type="InspectionType" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Amalfi inspection information entry that gather all the information use to retrieve the processed inspection in Amalfi addons.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="message">
								<xs:annotation>
									<xs:documentation>The inspection message formatted according to the contentType attribute.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="contentType">
												<xs:annotation>
													<xs:documentation>The content type of the message. Usually content type is set to 'text/plain".</xs:documentation>
												</xs:annotation>
											</xs:attribute>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="extraValues" minOccurs="0">
								<xs:annotation>
									<xs:documentation>This optional field is used to make explicit
the values  present in the message field</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="value" maxOccurs="unbounded">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="name" type="xs:string" use="required"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ReportType">
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element name="checkList" type="CheckListType">
				<xs:annotation>
					<xs:documentation>the list of checks</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="gippVersion" type="xs:token" use="required">
			<xs:annotation>
				<xs:documentation>The version of the GIPP used to produce this report.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="globalStatus" type="PassFailType" use="required">
			<xs:annotation>
				<xs:documentation>The global status of the inspections gathered into this report.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="date" type="xs:dateTime" use="required">
			<xs:annotation>
				<xs:documentation>The date of creation of this report.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== stienheremans/sen2like/sen2cor3/SEN2COR_3/cfg/L2A_QUALITY.xml
<?xml version="1.0" encoding="UTF-8"?>
<L2A_Quality_File xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				  xmlns="http://gs2.esa.int/DATA_STRUCTURE/l2aqiReport"
				  xsi:schemaLocation="http://gs2.esa.int/DATA_STRUCTURE/l2aqiReport L2A_QUALITY.xsd">
	<L2A_Quality_Header>
		<Fixed_Header>
			<File_Name>L2A_QUALITY</File_Name>
			<File_Description>Quality information obtained from Sen2Cor</File_Description>
			<Notes/>
			<Mission>S2A</Mission>
			<!-- This can be set to OPER or USER dependent on PDGS or Toolbox mode -->
			<File_Class>USER</File_Class>
			<File_Type>L2A_QLINFO</File_Type>
			<Validity_Period>
                <Validity_Start>UTC=2015-06-22T00:00:00</Validity_Start>
                <Validity_Stop>UTC=2100-01-01T00:00:00</Validity_Stop>
			</Validity_Period>
			<File_Version>1</File_Version>
			<Source>
				<System>Sen2Cor</System>
				<Creator>Sen2Cor</Creator>
				<Creator_Version>2.10</Creator_Version>
				<Creation_Date>UTC=0000-00-00T00:00:00</Creation_Date>
			</Source>
		</Fixed_Header>
	</L2A_Quality_Header>
	<Data_Block type="xml">
		<report gippVersion="1.0" globalStatus="PASSED" date="2001-12-17T09:30:47Z">
			<checkList>
				<parentID>L2A_SC</parentID>
				<name>SCENE_CLASS_QUALITY</name>
				<version>2.10</version>
				<item class="http://www.esa.int/s2#pdi_level_2a_tile_container"
					  className="PDI Level 2A Tile Folder"
					  name="NA"
					  url="NA"
				/>
				<check>
					<message contentType="text/plain">"Percentage of classified pixels"</message>
					<extraValues>
						<value name="CLOUDY_PIXEL_PERCENTAGE">NA</value>
						<value name="CLOUDY_PIXEL_OVER_LAND_PERCENTAGE">NA</value>
						<value name="DEGRADED_MSI_DATA_PERCENTAGE">NA</value>
						<value name="NODATA_PIXEL_PERCENTAGE">NA</value>
						<value name="SATURATED_DEFECTIVE_PIXEL_PERCENTAGE">NA</value>
						<value name="CAST_SHADOW_PERCENTAGE">NA</value>
						<value name="CLOUD_SHADOW_PERCENTAGE">NA</value>
						<value name="VEGETATION_PERCENTAGE">NA</value>
						<value name="NOT_VEGETATED_PERCENTAGE">NA</value>
						<value name="WATER_PERCENTAGE">NA</value>
						<value name="UNCLASSIFIED_PERCENTAGE">NA</value>
						<value name="MEDIUM_PROBA_CLOUDS_PERCENTAGE">NA</value>
						<value name="HIGH_PROBA_CLOUDS_PERCENTAGE">NA</value>
						<value name="THIN_CIRRUS_PERCENTAGE">NA</value>
						<value name="SNOW_ICE_PERCENTAGE">NA</value>
					</extraValues>
				</check>
			</checkList>
			<checkList>
				<parentID>L2A_AC</parentID>
				<name>ATMOSPHERIC_CORRECTION_QUALITY</name>
				<version>2.10</version>
				<item class="http://www.esa.int/s2#pdi_level_2a_tile_container"
					  className="PDI Level 2A Tile Folder"
					  name="NA"
					  url="NA"
				/>
				<check>
					<message contentType="text/plain">Atmospheric correction quality values</message>
					<extraValues>
						<value name="AOT_RETRIEVAL_ACCURACY">NA</value>
						<value name="GRANULE_MEAN_AOT">NA</value>
						<value name="WV_RETRIEVAL_ACCURACY">NA</value>
						<value name="GRANULE_MEAN_WV">NA</value>
						<value name="OZONE_VALUE">NA</value>
						<value name="START_VISIBILITY_KM">NA</value>
						<value name="VISIBILITY_FROM_DDV_KM">NA</value>
						<value name="FINAL_VISIBILITY_KM">NA</value>
						<value name="AVERAGE_SOLAR_ZENITH_ANGLE">NA</value>
						<value name="DDV_PIXEL_PERCENTAGE">NA</value>
						<value name="DDV_REFLECTANCE_RANGE">NA</value>
						<value name="BLUE_PATH_RADIANCE_RESCALING_FACTOR">NA</value>
					</extraValues>
				</check>
				<check>
					<message contentType="text/plain">Atmospheric correction quality control</message>
					<extraValues>
						<value name="AC_ENABLED">True</value>
						<!-- WV_RETRIEVAL_METHOD: SEN2COR_APDA | NA -->
						<value name="WV_RETRIEVAL_METHOD">SEN2COR_APDA</value>
						<!-- AOT_RETRIEVAL_METHOD: SEN2COR_DDV | CAMS | DEFAULT | NA-->
						<value name="AOT_RETRIEVAL_METHOD">NA</value>
						<value name="VISIBILITY_LESS_THAN_5_KM">NA</value>
						<value name="AOT_ABOVE_1">NA</value>
						<value name="GRANULE_WV_ABOVE_5_CM">NA</value>
					</extraValues>
				</check>
				<check>
					<message contentType="text/plain">Percentage of negative BOA pixels</message>
					<extraValues>
						<value name="B01">NA</value>
						<value name="B02">NA</value>
						<value name="B03">NA</value>
						<value name="B04">NA</value>
						<value name="B05">NA</value>
						<value name="B06">NA</value>
						<value name="B07">NA</value>
						<value name="B08">NA</value>
						<value name="B8A">NA</value>
						<value name="B11">NA</value>
						<value name="B12">NA</value>
					</extraValues>
				</check>
				<check>
					<message contentType="text/plain">Look up table file list</message>
					<extraValues>
						<value name="LUT_DATA_FILES">NA</value>
					</extraValues>
				</check>
			</checkList>
			<checkList>
				<parentID>L2A_AUX</parentID>
				<name>AUX_DATA_QUALITY</name>
				<version>2.10</version>
				<item class="http://www.esa.int/s2#pdi_level_2a_tile_container"
					  className="PDI Level 2A Tile Folder"
					  name="NA"
					  url="NA"
				/>				
				<check>
					<message contentType="text/plain">AUX related parameters</message>
					<extraValues>
						<!-- DEM_TYPE: SRTM_90 | DTED_90 | DTED_30 | (CDSE-AWS) COPERNICUS_90 | (CDSE-AWS) COPERNICUS_30 -->
						<value name="DEM_TYPE">NA</value>
						<value name="DEM_MEAN_ALTITUDE_KM">NA</value>
						<value name="DEM_MEAN_SLOPE">NA</value>
						<value name="GROUND_ELEVATION_ABOVE_3_KM">NA</value>
						<value name="SOLAR_ZENITH_ANGLE_ABOVE_70_DEG">NA</value>
						<!-- OZONE_SOURCE: AUX_ECMWFT | CONFIG | CAMS | OTHER  -->
						<value name="OZONE_SOURCE">NA</value>
					</extraValues>
				</check>
				<check>
					<message contentType="text/plain">AUX data file list</message>
					<extraValues>
						<value name="AUX_DATA_FILES">Available</value>
					</extraValues>
				</check>
			</checkList>
		</report>
	</Data_Block>
</L2A_Quality_File>
